src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="comments")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Jeux", inversedBy="comments")
     * //JoinCloumn (nullable =false)
     */
    private $jeux;

    /**
     * @ORM\Column(type="text")
     */
    private $comments_context;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $reports;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getJeux(): ?Jeux
    {
        return $this->jeux;
    }

    public function setJeux(?Jeux $jeux): self
    {
        $this->jeux = $jeux;

        return $this;
    }

    public function getCommentsContext(): ?string
    {
        return $this->comments_context;
    }

    public function setCommentsContext(string $comments_context): self
    {
        $this->comments_context = $comments_context;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getReports(): ?int
    {
        return $this->reports;
    }

    public function setReports(?int $reports): self
    {
        $this->reports = $reports;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"pseudo"}, message="Ce pseudo existe déja.")
 */
class User implements UserInterface 
{

    public function __toString()
    {
        return $this->email;
         //return $this->pseudo;
    }
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="user")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vote", mappedBy="user")
     */
    private $votes;

    /**
     * @ORM\Column(type="string", length=255, unique=true, nullable=true)
     */
    private $email;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $passwordRequestedAt;

    /**
    * @var string
    *
    * @ORM\Column(type="string", length=255, nullable=true)
    */
    private $token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *@var \DateTime
     */
    private $restricted;


    

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

  

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Vote[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setUser($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getUser() === $this) {
                $vote->setUser(null);
            }
        }

        return $this;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


     /*
     * Get passwordRequestedAt
     */
    public function getPasswordRequestedAt()
    {
        return $this->passwordRequestedAt;
    }

    /*
     * Set passwordRequestedAt
     */
    public function setPasswordRequestedAt($passwordRequestedAt)
    {
        $this->passwordRequestedAt = $passwordRequestedAt;
        return $this;
    }

    /*
     * Get token
     */
    public function getToken()
    {
        return $this->token;
    }

    /*
     * Set token
     */
    public function setToken($token)
    {
        $this->token = $token;
        return $this;
    }

    public function getRestricted()
    {
        return $this->restricted;
    }

    public function setRestricted($restricted)
    {
        $this->restricted = $restricted;

        return $this;
    }



}

src/Entity/Vote.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VoteRepository")
 */
class Vote
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="votes")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Jeux", inversedBy="votes")
     */
    private $jeux;

    /**
     * @ORM\Column(type="integer")
     */
    private $vote_value;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getJeux(): ?Jeux
    {
        return $this->jeux;
    }

    public function setJeux(?Jeux $jeux): self
    {
        $this->jeux = $jeux;

        return $this;
    }

    public function getVoteValue(): ?int
    {
        return $this->vote_value;
    }

    public function setVoteValue(int $vote_value): self
    {
        $this->vote_value = $vote_value;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\JeuxRepository;
use App\Entity\Jeux;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;

use App\Entity\User;
use App\Form\UserType;
use App\Form\EditPasswordType;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Form\FormError;



use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request; // permet de centraliser l'accès à toutes les super variables de PHP en une seule classe utilitaire
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\PaginatorInterface; // bundle KNP Paginator


class MainController extends AbstractController
{


    /**
     * @Route("/", name="accueil")
     */
    public function index()
    {

        $donnees = $this->getDoctrine()->getRepository(Jeux::class)->findBy([],['id' => 'desc']);

        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'jeux' => $donnees,

        ]);
    }
    

    /**
     * @Route("/category", name="category")
     *
     * affiche le propertyform + les jeux + la pagination sur page category
     */
    public function indexPaginator(Request $request, PaginatorInterface $paginator, JeuxRepository $jeuxRepository) // Nous ajoutons les paramètres requis
    {
       // $session->get('currentQuery');

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $jeuxParPage = 12;
      
            $firstTri = $request->get('firstTri');
            $numberTri = $request->get('numberTri');
            $categorie = $request->get('categorie');
            $nbJoueur = $request->get('nbJoueur');
            $duree = $request->get('duree');
            $age = $request->get('age');
            $motscle=$request->get('search');
            $prix=$request->get('prix');
            $categories=$request->get('jeuxes');
            
            $criteria = $form->getData();

        

            /*Je revérifie le nombres de jeux par page au cas où le get est modifier par un moyen quelconque */
             if (($numberTri == 12) || ($numberTri == 15) || ($numberTri == 18)){

                $jeuxParPage = $numberTri; 

            }
       

        if ( isset($categories) || isset($nbJoueur)  || isset($duree) || isset($age) || isset($firstTri) || isset($motscle) || isset($prix)){

            if (($categories != null) || ($nbJoueur != null) || ($duree != null) || ($age != null)  || ($firstTri != null)  || ($motscle != '')  || ($prix != null)){

                 $donnees = $this->getDoctrine()->getRepository(Jeux::class)->findJeuxBytri($nbJoueur, $duree, $age, $firstTri, $motscle, $categories,$prix ); 
            }
            else {

               
                    $donnees = $this->getDoctrine()->getRepository(Jeux::class)->findBy([],['id' => 'desc']);
                    
            }
            
        }

        else {

                 // Méthode findBy qui permet de récupérer les données avec des critères de filtre et de tri
                //Si aucun critères de recherches n'est actif je fais appel à la fonction findBy simplement
             
                    $donnees = $this->getDoctrine()->getRepository(Jeux::class)->findBy([],['id' => 'desc']);
              
              
            }


        $nbjeux = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)

            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            $jeuxParPage // Nombre de résultats par page
        );


        return $this->render('main/category.html.twig', [
            'jeux' => $nbjeux,
            'search' => $motscle,
            'form' => $form->createView()
        ]);
    }



    /**
     * @Route("/connexion", name="login")
     */
    public function connexion()
    {
        return $this->render('main/connexion.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }


   

    /**
     * @Route("/produit", name="produit")
     */
    public function produit()
    {
        return $this->render('main/produit.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }


    /**
     * @Route("/recherche", name="recherche")
     */
    public function recherche()
    {
        return $this->render('main/recherche.html.twig', [
            'controller_name' => 'MainController',
        ]);
    }


    /**
     * page logout
     *
     *@Route("/logout", name="logout")
     */
    public function logout(){

       $this->addFlash('success', 'Vous êtes déconnecté, à bientôt!');  
       return $this->render('main/index.html.twig');  

        
    }

}

templates/main/addAdmin.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}Admin - Ajout jeux{% endblock %}

{% block body %}

     {{ parent() }}
     

{% endblock %}


{% block content %}

    <h1 class="text-center">Nouveau Compte admin</h1>
   
<div class=" box-connect no-bg margin-auto">



    	{{ form_start(form) }}
    	{{ form_errors(form.pseudo) }}
    	{{ form_widget(form.pseudo, {'attr': {'placeholder': 'Pseudo', 'title': 'Indiquez un pseudo', 'class': 'userconnect'} }) }}

    	{{ form_errors(form.plainPassword) }}
    	{{ form_widget(form.plainPassword, {'attr': {'placeholder': 'Mot de passe', 'title': 'Indiquez un mot de passe', 'class': 'userconnect'} }) }}

    	{{ form_row(form.submit, {'attr': {'label': "Ajouter",  'class': 'connectbtn'} }) }}
    	{{ form_end(form) }}



    </div>
        	{% for message in app.flashes('success') %}
    		<div class="alert alert-success">
    			{{ message }}
    		</div>
    	{% endfor %}
    
    
</div>

        
   

    
{% endblock %}
         

templates/main/category.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Page d'acceuil{% endblock %}

{% block body %}

   {{ parent() }}
   

{% endblock %}

  {% block content %}
    <section class="cat_product_area section_gap">
      <div class="container">
        <div class="row flex-row-reverse">
          <div class="col-lg-9">
            <div class="product_top_bar">
              <div class="left_dorp">
                {{ form_start(form) }}
                {{ form_widget(form.firstTri) }}
               
               

                {{ form_widget(form.numberTri, {'attr': {'class': 'margin-left-20'} }) }}
              
               <ul class="navbar-right pull-right allRightNav">

                {% if  (search is defined) %}
                  {% if search != "" %}
                  <p class="bold searchbar allRightNav">Rechercher: "{{search}}"</p> 
                  {% endif %}
                {% endif %}
                  
                
              </ul>
            



      

      



              </div>

              {% block searchForm %}
              {% endblock %}


            

              


               
            


                


            </div>

            <div class="latest_product_inner">
              <div class="row">




                {% for jeu in jeux %}


                <div class="col-lg-4 col-md-6">
                  <div class="single-product">
                    <div class="product-img">
                     <a href="{{ path('category_id', {'id': jeu.id}) }}"><img
                      class="card-img"
                      src="{{jeu.image}}"
                      alt="{{jeu.nom}}"/></a>
                      <div class="p_icon">
                        <a href="{{ path('category_id', {'id': jeu.id}) }}">
                          <i class="ti-eye"></i>
                        </a>
                             <!--
                          <a href="#">
                            <i class="ti-heart"></i>
                          </a>
                        
                          <a href="#">
                            <i class="ti-shopping-cart"></i>
                          </a>
                        -->
                        
                      </div>
                    </div>
                    <div class="product-btm">
                      <a href="#" class="d-block">
                        <h4>{{jeu.nom}}</h4>
                      </a>
                      <div class="mt-3">
                        <span class="mr-4">{{jeu.prix}} €</span>
                        
                      </div>
                    </div>
                  </div>
                </div>
                 
               
                {% endfor %}
                  {{ knp_pagination_render(jeux) }}

        
           

                <div class="main">
                
                    
                   
                 
                  <!--
                  <div id="pagination">
                    <a class="page" href="#">&laquo;</a>
                    <a class="page" href="#">1</a>
                    <a class="page active" href="#">2</a>
                    <a class="page" href="#">3</a>
                    <a class="page" href="#">4</a>
                    <a class="page" href="#">5</a>
                    <a class="page" href="#">6</a>
                    <a class="page" href="#">&raquo;</a>
                  </div>
                -->
                </div>
              


              </div>


            </div>

          </div>
           






          <div class="col-lg-3">
            <div class="left_sidebar_area">
              <aside class="left_widgets p_filter_widgets">
                <div class="l_w_title">
                  <h3>Catégories</h3>
                </div>
                <div class="widgets_inner">
                  <ul class="list">
                     {{ form_widget(form.jeuxes, {'attr': {'class': ''} }) }}
                   

               </ul>
             </div>
           </aside>

           <aside class="left_widgets p_filter_widgets">
            <div class="l_w_title">
             <h3>Nombres de joueurs</h3>
           </div>
           <div class="widgets_inner">
            <ul class="list">
              {{ form_widget(form.nbJoueur) }}

         </ul>
       </div>
     </aside>

     <aside class="left_widgets p_filter_widgets">
      <div class="l_w_title">
        <h3>Durée</h3>
      </div>
      <div class="widgets_inner">
        <ul class="list">
          {{ form_widget(form.duree) }}
         
      </ul>
    </div>
  </aside>


 

  <aside class="left_widgets p_filter_widgets special-width-age-container">
    <div class="l_w_title">
     <h3>Âge</h3>
   </div>
   <div class="widgets_inner">
    <div id="container-text-age">

      <div class="review_box">
        <p id="age-text">Jusque:</p> <p id="text-age-choice"></p>
      </div>
    </div>
    <div class="clear">
    </div>

    <ul class="ul-age">
      {{ form_widget(form.age, {'attr': {'class': ''} }) }}


   </ul>


 </div>
</aside>


<aside class="left_widgets p_filter_widgets">
  <div class="l_w_title">
    <h3>Prix</h3>
  </div>
  <div class="widgets_inner">
    <div class="range_item">
      <div id="slider-range"></div>
     <!-- <div class="">-->
     <p class="float-left">Moins de: &nbsp</p> <div id="f"></div>
      <p class="float-left">€</p>
     <div class="slidecontainer">
        {{ form_widget(form.prix, {'attr': {'class': ''} }) }}
      </div>
       <!-- <label for="amount">Price : </label>
        <input type="text" id="amount" readonly />-->
        <div class="display-none">
          {{ form_widget(form.tri)}}
        </div>
      <!-- <button class="filtre">rechercher</button>-->
            
            {{ form_end(form) }}
       
    <!-- </div>-->
    </div>
  </div>
</aside>
</div>
</div>

</div>


</div>

</div>




</section>
{% endblock %}
{% block javascriptAdd %} <script src="{{asset('js/searchOnClick.js')}}"></script>{% endblock %}

templates/main/compte.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block body %}

	 {{ parent() }}
	 

{% endblock %}


{% block content %}

    <section class="new_product_area section_gap_top section_gap_bottom_custom">
  

      <div class="row margin auto">
        <div class="col-lg-6 margin-auto">
          <div class="box-account no-bg margin-auto">
            <div class="choice-account">
              <div class="title-account titlea-current">
               <a class="title-a" href="{{ path('compte') }}">Mon compte</a>
              </div>
              <div class="title-account">
               <a class="title-a" href="{{ path('myVotes') }}">Mes votes</a>
                </div>
               <div class="title-account">
               <a class="title-a" href="{{ path('myComments') }}">Mes avis</a>
                </div>

            </div>
            <h5 class="text-uppercase text-center">Mon compte</h5>

            <p class="p-account">Pseudo:</p> <p>{{ app.user.username }}</p>
            <p class="p-account">E-mail:</p>
             <p>
              {% if (app.user.email) %}
                  {{ app.user.email }} <button id="showFormEmail" >Modifier e-mail</button></br>
                 

                   <div id="showForm" class="display-none">
                     {{ form_start(form) }}
                         {{ form_widget(form.email, {'attr': {'placeholder':'Inscris ton e-mail ici', 'class': ''} }) }}
                         {{ form_widget(form.submit, {'attr': {'class': ''} }) }}

                     {{ form_end(form) }}
                     <a class="black margin-left-195 " href="{{ path('compte') }}" class="display-none">Annuler</a></br>
                   </div>

                  {% for message in app.flashes('success') %}
                      <div class="alert alert-success">
                        {{ message }}
                      </div>
                  {% endfor %}

                  {% for message in app.flashes('error') %}
                      <div class="alert alert-danger">
                        {{ message }}
                      </div>
                  {% endfor %}


                    <a class="cancel" href="{{ path('deleteEmail') }}">dissocier cet email</a></br>

              {% else %}<p>
                    <button id="showFormEmail" >Ajouter un e-mail</button></br>

                    <div id="showForm" class="display-none">
                     {{ form_start(form) }}
                         {{ form_widget(form.email, {'attr': {'placeholder':'Inscris ton e-mail ici', 'class': ''} }) }}
                         {{ form_widget(form.submit, {'attr': {'class': ''} }) }}

                     {{ form_end(form) }}
                     <a class="cancel" href="{{ path('compte') }}" class="display-none">Annuler</a></br>
                   </div>
             {% endif %}
   


              <a  href="{{ path('editPassword') }}" >Modifier mot de passe</a></br>

              {% if (app.user.email == null) %}
                <i>NB: Ajouter un e-mail vous permettra de récupérer votre compte en cas d'oubli du mot de passe.</i>
              {% endif %}
         
              
          </div>
          
        </div>

        
      </div>
    </div>
  </section>

	 

{% endblock %}

templates/main/myComments.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mon compte - Mes avis{% endblock %}

{% block body %}

	 {{ parent() }}
	 

{% endblock %}


{% block content %}

    <section class="new_product_area section_gap_top section_gap_bottom_custom">
  

      <div class="row margin auto">
        <div class="col-lg-6 margin-auto">
          <div class="box-account no-bg margin-auto">
            <div class="choice-account">
              <div class="title-account">
               <a class="title-a" href="{{ path('compte') }}">Mon compte</a>
              </div>
              <div class="title-account">
               <a class="title-a" href="{{ path('myVotes') }}">Mes votes</a>
                </div>
               <div class="title-account titlea-current">
               <a class="title-a" href="{{ path('myComments') }}">Mes avis</a>
                </div>

            </div>
            <h5 class="text-uppercase text-center">Mes avis</h5>


            {% if comments != null %}

            <table class="table">
                <thead>
                  <tr>

                    <th></th>
                    <th>Jeu</th>
                    <th>Avis</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for comment in comments %}
                    <tr>
                      <td><img class="width-30" src="{{ comment.jeux.image }}" alt="{{ comment.jeux.image }}"></td>
                      <td>{{ comment.jeux.nom  }}</td>
                      <td><p class="showDate">{{comment.createAt|date("d/m/Y à H:i") }}</p>{{ comment.commentsContext }}</td>


                      <td>


                     <form method="post" action="{{ path('deleteComments', {'id': comment.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet avis ?');">
                          <input type="hidden" name="_method" value="DELETE">
                          <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
                          <button class="btn-del">Supprimer</button>
                    </form>

                   

                     </td>
                   </tr>

                 {% else %}
                  <tr>
                    <td colspan="9">pas d'enregistrement trouvé</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>



          {% else %}

           <p class=" text-center">vous n'avez encore soumis un commentaire.</p>
         {% endif %}

         
              
          </div>
          
        </div>

        
      </div>
    </div>
  </section>

	 

{% endblock %}

templates/main/myVotes.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mon compte - Mes votes{% endblock %}

{% block body %}

	 {{ parent() }}
	 

{% endblock %}


{% block content %}

    <section class="new_product_area section_gap_top section_gap_bottom_custom">
  

      <div class="row margin auto">
        <div class="col-lg-6 margin-auto">
          <div class="box-account no-bg margin-auto">
            <div class="choice-account">
              <div class="title-account">
               <a class="title-a" href="{{ path('compte') }}">Mon compte</a>
              </div>
              <div class="title-account titlea-current">
               <a class="title-a" href="{{ path('myVotes') }}">Mes votes</a>
                </div>
               <div class="title-account">
               <a class="title-a" href="{{ path('myComments') }}">Mes avis</a>
                </div>

            </div>
            <h5 class="text-uppercase text-center">Mes votes</h5>

            {% if votes != null %}

            <table class="table">
                <thead>
                  <tr>

                    <th></th>
                    <th>Jeu</th>
                    <th>Note Attribuée</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for vote in votes %}
                    <tr>
                      <td><img class="width-30" src="{{ vote.jeux.image }}" alt="{{ vote.jeux.image }}"></td>
                      <td>{{ vote.jeux.nom  }}</td>
                      <td>
                        {% set i = 0 %}


                        {% for i in 0..4 %}

                          {% if vote.voteValue > i %}


                            <svg height="21" id="Calque_1" data-name="Calque 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 95.11 90.52"><polygon class="cls-1" points="47.46 74.44 18.69 89.47 24.26 57.49 1.07 34.78 33.2 30.2 47.63 1.13 61.93 30.27 94.03 35.01 70.73 57.61 76.14 89.61 47.46 74.44" fill="orange" stroke="DimGray"/></svg>

                          

                           {% else %}

                            <svg height="21" id="Calque_1" data-name="Calque 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 95.11 90.52"><polygon class="cls-1" points="47.46 74.44 18.69 89.47 24.26 57.49 1.07 34.78 33.2 30.2 47.63 1.13 61.93 30.27 94.03 35.01 70.73 57.61 76.14 89.61 47.46 74.44" fill="#ebf1f0" stroke="DimGray" /></svg>


                          {% endif %}

                        {% endfor %}




                      </td>


                      <td>

                      <form method="post" action="{{ path('deleteVotes', {'id': vote.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette note ?');">
                          <input type="hidden" name="_method" value="DELETE">
                          <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vote.id) }}">
                          <button class="btn-del">Supprimer</button>
                      </form>

                      <!--  <a class="grey" href="{{ path('deleteEmail') }}">Supprimer</a></br>-->

                     </td>
                   </tr>

                 {% else %}
                  <tr>
                    <td colspan="9">pas d'enregistrement trouvé</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>



          {% else %}

           <p class=" text-center">vous n'avez encore noté aucun jeu.</p>
         {% endif %}



    

                    
          </div>
          
        </div>

        
      </div>
    </div>
  </section>

	 

{% endblock %}