src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_cat;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Jeux", mappedBy="categories")
     */
    private $jeuxes;

    public function __construct()
    {
        $this->jeuxes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCat(): ?string
    {
        return $this->nom_cat;
    }

    public function setNomCat(string $nom_cat): self
    {
        $this->nom_cat = $nom_cat;

        return $this;
    }

    public function __toString(){
        // Or change the property that you want to show in the select.
        return $this->nom_cat;
    }

    /**
     * @return Collection|Jeux[]
     */
    public function getJeuxes(): Collection
    {
        return $this->jeuxes;
    }

    public function addJeux(Jeux $jeux): self
    {
        if (!$this->jeuxes->contains($jeux)) {
            $this->jeuxes[] = $jeux;
        }

        return $this;
    }

    public function removeJeux(Jeux $jeux): self
    {
        if ($this->jeuxes->contains($jeux)) {
            $this->jeuxes->removeElement($jeux);
        }

        return $this;
    }
}

src/Entity/Jeux.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\JeuxRepository")
 */
class Jeux
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $age_min;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_joueur_min;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_joueur_max;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $prix;

   

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;


    /**
     * @ORM\Column(type="string", length=2000)
     */
    private $description;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\ImagesAlt", cascade={"persist", "remove"})
     */
    private $image_alt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="jeux", cascade={"remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Vote", mappedBy="jeux", cascade={"remove"})
     */
    private $votes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="jeuxes", fetch="EAGER")  
     * 
     */
    private $categories;

     
    

    

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->votes = new ArrayCollection();
        $this->categories = new ArrayCollection();
        
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAgeMin(): ?int
    {
        return $this->age_min;
    }

    public function setAgeMin(int $age_min): self
    {
        $this->age_min = $age_min;

        return $this;
    }

    public function getNbJoueurMin(): ?int
    {
        return $this->nb_joueur_min;
    }

    public function setNbJoueurMin(int $nb_joueur_min): self
    {
        $this->nb_joueur_min = $nb_joueur_min;

        return $this;
    }

    public function getNbJoueurMax(): ?int
    {
        return $this->nb_joueur_max;
    }

    public function setNbJoueurMax(int $nb_joueur_max): self
    {
        $this->nb_joueur_max = $nb_joueur_max;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

  
/*
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
    */
     public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImageAlt(): ?ImagesAlt
    {
        return $this->image_alt;
    }

    public function setImageAlt(?ImagesAlt $image_alt): self
    {
        $this->image_alt = $image_alt;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setJeux($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getJeux() === $this) {
                $comment->setJeux(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Vote[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }

    public function addVote(Vote $vote): self
    {
        if (!$this->votes->contains($vote)) {
            $this->votes[] = $vote;
            $vote->setJeux($this);
        }

        return $this;
    }

    public function removeVote(Vote $vote): self
    {
        if ($this->votes->contains($vote)) {
            $this->votes->removeElement($vote);
            // set the owning side to null (unless already changed)
            if ($vote->getJeux() === $this) {
                $vote->setJeux(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addJeux($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            $category->removeJeux($this);
        }

        return $this;
    }

  




}

src/Controller/JeuxController.php
<?php

namespace App\Controller;

use App\Entity\Jeux;
use App\Entity\ImagesAlt;
use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use App\Form\JeuxType;
use App\Service\FileUploader;
use App\Service\FileUploaderAlt;
use App\Repository\JeuxRepository;
use App\Entity\Comments;
use App\Repository\CommentsRepository;
use App\Repository\ImagesAltRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class JeuxController extends AbstractController
{
    /**
     * @Route("/", name="jeux_index", methods={"GET"})
     */
    public function index(JeuxRepository $jeuxRepository, CategoryRepository $categoryRepository): Response
    {

        return $this->render('jeux/index.html.twig', [
            'jeuxes' => $jeuxRepository->findAll(),
            'categories' => $categoryRepository->findAll(),
            
        ]);
    }

    /**
     * @Route("/new", name="jeux_new", methods={"GET","POST"})
     */
    public function new(Request $request, FileUploader $fileUploader, FileUploaderAlt $fileUploaderAlt, CategoryRepository $categoryRepository): Response
    {
        $jeux = new Jeux();
        $form = $this->createForm(JeuxType::class, $jeux);
        $form->handleRequest($request);


        $category = new Category();
        $formCat = $this->createForm(CategoryType::class, $category);
        $formCat->handleRequest($request);



         if ($formCat->isSubmitted() && $formCat->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $category->setNomCat($category);

            $entityManager->persist($category);
            $entityManager->flush();

         }


        if ($form->isSubmitted() && $form->isValid()) {


            /******             Uploads                         ******/
          
            $image = $form['image']->getData();
           
         



            if ($image) {
                $imageFileName = $fileUploader->upload($image);
                 $jeux->setimage('/symfony/uploads/images/' .$imageFileName);
            }

            $imageAlt = new ImagesAlt();
            $image2 = $form->get('image2')->getData();        
              
            if ($image2) {
               
                $image2FileName = $fileUploaderAlt->upload($image2);
                 $imageAlt->setImage2('/symfony/uploads/alt_images/' .$image2FileName);
                 $jeux->setImageAlt($imageAlt);
            }

            $image3 = $form->get('image3')->getData(); 

            if ($image3) {
               
                $image3FileName = $fileUploaderAlt->upload($image3);
                 $imageAlt->setImage3('/symfony/uploads/alt_images/' .$image3FileName);
                 $jeux->setImageAlt($imageAlt);
            }
        

            /****                Ends upload                              ****/




            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($jeux);
            $entityManager->flush();

            return $this->redirectToRoute('jeux_index');
        }

        return $this->render('jeux/new.html.twig', [
            'jeux' => $jeux,
            'category' => $categoryRepository->findAll(),
            'formCat' => $formCat->createView(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="jeux_show", methods={"GET"})
     */
    public function show(Jeux $jeux): Response
    {

        $em=$this->getDoctrine()->getManager();
        $jeuxcat = $em->getRepository(Jeux::class)->find('1');

        return $this->render('jeux/show.html.twig', [
            'jeux' => $jeux,
            'jeuxcat' => $jeuxcat,
            
        ]);
    }

    /**
     * @Route("/{id}/edit", name="jeux_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Jeux $jeux, FileUploader $fileUploader, FileUploaderAlt $fileUploaderAlt, CategoryRepository $categoryRepository): Response
    {
        $form = $this->createForm(JeuxType::class, $jeux);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            /******             Uploads                         ******/

            $image = $form['image']->getData();
           

        if ($image) {
            $imageFileName = $fileUploader->upload($image);
             $jeux->setimage('/symfony/uploads/images/' .$imageFileName);
        }

        $imageAlt=$jeux->getImageAlt();
        $image2 = $form->get('image2')->getData();        
          
        if ($image2) {
           
            $image2FileName = $fileUploaderAlt->upload($image2);
             $imageAlt->setImage2('/symfony/uploads/alt_images/' .$image2FileName);
             $jeux->setImageAlt($imageAlt);
        }

        $image3 = $form->get('image3')->getData(); 

        if ($image3) {
           
            $image3FileName = $fileUploaderAlt->upload($image3);
             $imageAlt->setImage3('/symfony/uploads/alt_images/' .$image3FileName);
             $jeux->setImageAlt($imageAlt);
        }
        
        
        /******             Ends Uploads Edit                         ******/

            
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('jeux_index');
        }

        return $this->render('jeux/edit.html.twig', [
            'jeux' => $jeux,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="jeux_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Jeux $jeux): Response
    {
        if ($this->isCsrfTokenValid('delete'.$jeux->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($jeux);
            $entityManager->flush();
        }

        return $this->redirectToRoute('jeux_index');
    }




    
}

templates/jeux/_delete_form.html.twig
<form method="post" action="{{ path('jeux_delete', {'id': jeux.id}) }}" onsubmit="return confirm('Es-tu sûr de vouloir supprimer ce jeux ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ jeux.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/jeux/_form.html.twig
	

	
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/jeux/edit.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}ADMIN - Accueil{% endblock %}

{% block body %}

     {{ parent() }}
     

{% endblock %}


{% block content %}

    <h1>Edit - Liste des jeux</h1>
   
<img class="img-310" src="{{ jeux.image }}" alt="{{ jeux.nom }}">

    {{ include('jeux/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    
    	

    <a href="{{ path('jeux_index') }}">Retour liste</a>

    {{ include('jeux/_delete_form.html.twig') }}
   

    
{% endblock %}

templates/jeux/index.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}ADMIN - Accueil{% endblock %}

{% block body %}

     {{ parent() }}
     

{% endblock %}


{% block content %}

    <h1>Admin - Liste des jeux</h1>
       <a href="{{ path('jeux_new') }}">Ajouter nouveau jeu</a>
   

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Age_min</th>
                <th>Nb_joueur_min</th>
                <th>Nb_joueur_max</th>
                <th>Duree</th>
                <th>Prix</th>
                <th>image</th>
                <th>Catégories</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for jeux in jeuxes %}
            <tr>
                <td>{{ jeux.id }}</td>
                <td>{{ jeux.nom }}</td>
                <td>{{ jeux.ageMin }}</td>
                <td>{{ jeux.nbJoueurMin }}</td>
                <td>{{ jeux.nbJoueurMax }}</td>
                <td>{{ jeux.duree }}</td>
                <td>{{ jeux.prix }}</td>
             
                <td><img class="img-310" src="{{ jeux.image }}" alt="{{ jeux.nom }}">
                    <!-- miniature , image alternatives 1 et 2 -->
                    {% if jeux.imageAlt.image2 is defined%}
                        <img class="img-60" src="{{jeux.imageAlt.image2}}">
                     {% endif %}
                    {% if jeux.imageAlt.image3 is defined%}
                        <img class="img-60" src="{{jeux.imageAlt.image3}}">
                    {% endif %}

                 </td>
                
                 <td> 
                   
                        {% for jeux in jeux.getCategories() %}
                          
                         
                              {{ jeux.nomCat }}
                         

                         
                        {% endfor %}
                </td> 
                <td>{{ jeux.description }}</td>
                
                <td>
                    <a href="{{ path('jeux_show', {'id': jeux.id}) }}">Voir</a>
                    <a href="{{ path('jeux_edit', {'id': jeux.id}) }}">Modifier</a>
                    {{ include('jeux/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">pas d'enregistrement trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('jeux_new') }}">Ajouter nouveau jeu</a>
{% endblock %}

templates/jeux/new.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}Admin - Ajout jeux{% endblock %}

{% block body %}

     {{ parent() }}
     

{% endblock %}


{% block content %}

    <h1>Nouveau jeu</h1>
   


    {{ include('jeux/_form.html.twig') }}

    <a href="{{ path('jeux_index') }}">Retour liste</a>
   

    
{% endblock %}

templates/jeux/show.html.twig
{% extends 'layout-admin.html.twig' %}

{% block title %}ADMIN - Accueil{% endblock %}

{% block body %}

     {{ parent() }}
     

{% endblock %}


{% block content %}

   
       <h1>Jeux</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ jeux.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ jeux.nom }}</td>
            </tr>
            <tr>
                <th>Age_min</th>
                <td>{{ jeux.ageMin }}</td>
            </tr>
            <tr>
                <th>Nb_joueur_min</th>
                <td>{{ jeux.nbJoueurMin }}</td>
            </tr>
            <tr>
                <th>Nb_joueur_max</th>
                <td>{{ jeux.nbJoueurMax }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ jeux.duree }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ jeux.prix }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ jeux.image }}</td>
            </tr>
            <tr>
                <th>catégorie</th>
                <td> 
                   
                      
                        {% for jeux in jeux.getCategories() %}
                          
                         
                              {{ jeux.nomCat }}
                         

                         
                        {% endfor %}

                         
                   
                    

                    </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('jeux_index') }}">retour</a>

    <a href="{{ path('jeux_edit', {'id': jeux.id}) }}">Modifier</a>

    {{ include('jeux/_delete_form.html.twig') }}

    
{% endblock %}